#!/usr/bin/env bash

read -rp "Name of target drive: /dev/" TARGET_DRIVE
TARGET_DRIVE="/dev/${TARGET_DRIVE}"

read -rp "Computer name: " COMPUTER_NAME
read -rp "Username to create: " USERNAME

while true; do
  read -rsp "Password for ${USERNAME}: " USER_PASSWORD
  echo
  read -rsp "Password for ${USERNAME} (again): " USER_PASSWORD_CONFIRMATION
  echo

  [ -z "${USER_PASSWORD}${USER_PASSWORD_CONFIRMATION}" ] && echo "Password may not be empty" && continue
  [ "${USER_PASSWORD}" = "${USER_PASSWORD_CONFIRMATION}" ] && break
  echo "Passwords entered do not match.  Please try again"
done
